name = "evroskot-new"
main = "dist/server/worker.js"
compatibility_date = "2025-11-13"

[vars]
VK_ACCESS_TOKEN = "" # подставится из секретов

[[routes]]
pattern = "evroskot.ru/*"
zone_name = "evroskot.ru"

[[kv_namespaces]]
binding = "SESSION"
id = "1474923ec1d348cda14126bd3f9d6d10"