name = "evroskot"

compatibility_date = "2024-11-13"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

# Route
#[[routes]]
#pattern = "new.evroskot.ru/*"
#zone_name = "evroskot.ru"

# Static assets
[assets]
directory = "./dist/client"
binding = "ASSETS"

# KV Sessions
[[kv_namespaces]]
binding = "SESSION"
id = "1474923ec1d348cda14126bd3f9d6d10"

# Observability
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1